sudo: required
language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "clean-automation"
    token: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=deusemarjunior_truck-management

before_install:
- chmod +x mvnw