sudo: required
language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "clean-automation"
    token: $SONAR_TOKEN

jobs:
  include:
    - stage: Tests
      script:
      - ./mvnw test
    - stage: Sonar
      script:
      - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=deusemarjunior_truck-management
    - stage: Deploy
      deploy:
        provider: heroku
        api-key: 
          secure: $HEROKU_API_KEY
        app: truck-management

before_install:
- chmod +x mvnw