sudo: required
language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "clean-automation"
    token: $SONAR_TOKEN

script:
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=deusemarjunior_truck-management
